// AUTO-GENERATED BY UnityPlayerScan.py
#ifndef AUTOGEN_STUBS_H
#define AUTOGEN_STUBS_H

#include <stdint.h>

extern "C" void Thunk_AdjustWindowRectEx();
extern "C" void Thunk_AllowSetForegroundWindow();
extern "C" void Thunk_BCryptGenRandom();
extern "C" void Thunk_CancelIo();
extern "C" void Thunk_CertAddEncodedCertificateToStore();
extern "C" void Thunk_CertCloseStore();
extern "C" void Thunk_CertFreeCertificateChain();
extern "C" void Thunk_CertFreeCertificateContext();
extern "C" void Thunk_CertGetCertificateChain();
extern "C" void Thunk_CertOpenStore();
extern "C" void Thunk_CertVerifyCertificateChainPolicy();
extern "C" void Thunk_CheckDlgButton();
extern "C" void Thunk_ChoosePixelFormat();
extern "C" void Thunk_ClientToScreen();
extern "C" void Thunk_ClipCursor();
extern "C" void Thunk_CloseClipboard();
extern "C" void Thunk_CloseHandle();
extern "C" void Thunk_CoCreateFreeThreadedMarshaler();
extern "C" void Thunk_CoCreateGuid();
extern "C" void Thunk_CoCreateInstance();
extern "C" void Thunk_CoInitialize();
extern "C" void Thunk_CoSetProxyBlanket();
extern "C" void Thunk_CoTaskMemAlloc();
extern "C" void Thunk_CoTaskMemFree();
extern "C" void Thunk_CoUninitialize();
extern "C" void Thunk_CommandLineToArgvW();
extern "C" void Thunk_CompareStringW();
extern "C" void Thunk_CopyFileW();
extern "C" void Thunk_CopyImage();
extern "C" void Thunk_CopyRect();
extern "C" void Thunk_CreateBitmap();
extern "C" void Thunk_CreateDIBSection();
extern "C" void Thunk_CreateDialogParamA();
extern "C" void Thunk_CreateDialogParamW();
extern "C" void Thunk_CreateDirectoryW();
extern "C" void Thunk_CreateEventA();
extern "C" void Thunk_CreateEventW();
extern "C" void Thunk_CreateFileA();
extern "C" void Thunk_CreateFileW();
extern "C" void Thunk_CreateIconIndirect();
extern "C" void Thunk_CreateIoCompletionPort();
extern "C" void Thunk_CreateMutexA();
extern "C" void Thunk_CreatePipe();
extern "C" void Thunk_CreateProcessW();
extern "C" void Thunk_CreateSemaphoreW();
extern "C" void Thunk_CreateThread();
extern "C" void Thunk_CreateToolhelp32Snapshot();
extern "C" void Thunk_CreateWaitableTimerA();
extern "C" void Thunk_CreateWindowExW();
extern "C" void Thunk_CryptAcquireContextA();
extern "C" void Thunk_CryptCreateHash();
extern "C" void Thunk_CryptDestroyHash();
extern "C" void Thunk_CryptDestroyKey();
extern "C" void Thunk_CryptEncrypt();
extern "C" void Thunk_CryptGenRandom();
extern "C" void Thunk_CryptGetHashParam();
extern "C" void Thunk_CryptHashData();
extern "C" void Thunk_CryptImportKey();
extern "C" void Thunk_CryptReleaseContext();
extern "C" void Thunk_DebugBreak();
extern "C" void Thunk_DecodePointer();
extern "C" void Thunk_DefWindowProcW();
extern "C" void Thunk_DeleteCriticalSection();
extern "C" void Thunk_DeleteFileW();
extern "C" void Thunk_DeleteObject();
extern "C" void Thunk_DeregisterEventSource();
extern "C" void Thunk_DestroyCursor();
extern "C" void Thunk_DestroyIcon();
extern "C" void Thunk_DestroyWindow();
extern "C" void Thunk_DialogBoxParamA();
extern "C" void Thunk_DialogBoxParamW();
extern "C" void Thunk_DispatchMessageA();
extern "C" void Thunk_DispatchMessageW();
extern "C" void Thunk_DragDetect();
extern "C" void Thunk_DuplicateHandle();
extern "C" void Thunk_DwmGetWindowAttribute();
extern "C" void Thunk_EmptyClipboard();
extern "C" void Thunk_EnableWindow();
extern "C" void Thunk_EncodePointer();
extern "C" void Thunk_EndDialog();
extern "C" void Thunk_EnterCriticalSection();
extern "C" void Thunk_EnumDisplayDevicesA();
extern "C" void Thunk_EnumDisplayMonitors();
extern "C" void Thunk_EnumDisplaySettingsA();
extern "C" void Thunk_EnumDisplaySettingsW();
extern "C" void Thunk_EnumSystemLocalesW();
extern "C" void Thunk_EnumWindows();
extern "C" void Thunk_ExitProcess();
extern "C" void Thunk_ExitThread();
extern "C" void Thunk_ExpandEnvironmentStringsA();
extern "C" void Thunk_ExpandEnvironmentStringsW();
extern "C" void Thunk_FileTimeToSystemTime();
extern "C" void Thunk_FindClose();
extern "C" void Thunk_FindFirstFileExW();
extern "C" void Thunk_FindFirstFileW();
extern "C" void Thunk_FindNextFileW();
extern "C" void Thunk_FlushConsoleInputBuffer();
extern "C" void Thunk_FlushFileBuffers();
extern "C" void Thunk_FormatMessageA();
extern "C" void Thunk_FormatMessageW();
extern "C" void Thunk_FreeEnvironmentStringsW();
extern "C" void Thunk_FreeLibrary();
extern "C" void Thunk_FreeLibraryAndExitThread();
extern "C" void Thunk_GetACP();
extern "C" void Thunk_GetActiveWindow();
extern "C" void Thunk_GetAncestor();
extern "C" void Thunk_GetAsyncKeyState();
extern "C" void Thunk_GetCPInfo();
extern "C" void Thunk_GetCaretBlinkTime();
extern "C" void Thunk_GetClientRect();
extern "C" void Thunk_GetClipboardData();
extern "C" void Thunk_GetCommandLineA();
extern "C" void Thunk_GetCommandLineW();
extern "C" void Thunk_GetComputerNameW();
extern "C" void Thunk_GetConsoleCP();
extern "C" void Thunk_GetConsoleMode();
extern "C" void Thunk_GetCurrentDirectoryA();
extern "C" void Thunk_GetCurrentDirectoryW();
extern "C" void Thunk_GetCurrentProcess();
extern "C" void Thunk_GetCurrentProcessId();
extern "C" void Thunk_GetCurrentThread();
extern "C" void Thunk_GetCurrentThreadId();
extern "C" void Thunk_GetCursorPos();
extern "C" void Thunk_GetDC();
extern "C" void Thunk_GetDesktopWindow();
extern "C" void Thunk_GetDeviceCaps();
extern "C" void Thunk_GetDiskFreeSpaceExW();
extern "C" void Thunk_GetDlgItem();
extern "C" void Thunk_GetDriveTypeW();
extern "C" void Thunk_GetEnvironmentStringsW();
extern "C" void Thunk_GetEnvironmentVariableA();
extern "C" void Thunk_GetExitCodeProcess();
extern "C" void Thunk_GetFileAttributesA();
extern "C" void Thunk_GetFileAttributesExW();
extern "C" void Thunk_GetFileAttributesW();
extern "C" void Thunk_GetFileInformationByHandle();
extern "C" void Thunk_GetFileSize();
extern "C" void Thunk_GetFileType();
extern "C" void Thunk_GetFileVersionInfoA();
extern "C" void Thunk_GetFileVersionInfoSizeA();
extern "C" void Thunk_GetFocus();
extern "C" void Thunk_GetFullPathNameW();
extern "C" void Thunk_GetKeyNameTextW();
extern "C" void Thunk_GetKeyState();
extern "C" void Thunk_GetKeyboardLayoutNameW();
extern "C" void Thunk_GetLastError();
extern "C" void Thunk_GetLocalTime();
extern "C" void Thunk_GetLocaleInfoW();
extern "C" void Thunk_GetMessageA();
extern "C" void Thunk_GetMessageExtraInfo();
extern "C" void Thunk_GetMessagePos();
extern "C" void Thunk_GetMessageTime();
extern "C" void Thunk_GetModuleFileNameA();
extern "C" void Thunk_GetModuleFileNameW();
extern "C" void Thunk_GetModuleHandleA();
extern "C" void Thunk_GetModuleHandleExW();
extern "C" void Thunk_GetModuleHandleW();
extern "C" void Thunk_GetMonitorInfoA();
extern "C" void Thunk_GetMonitorInfoW();
extern "C" void Thunk_GetOEMCP();
extern "C" void Thunk_GetObjectA();
extern "C" void Thunk_GetOverlappedResult();
extern "C" void Thunk_GetParent();
extern "C" void Thunk_GetProcAddress();
extern "C" void Thunk_GetProcessHeap();
extern "C" void Thunk_GetProcessId();
extern "C" void Thunk_GetProcessWindowStation();
extern "C" void Thunk_GetQueuedCompletionStatus();
extern "C" void Thunk_GetRawInputData();
extern "C" void Thunk_GetRawInputDeviceInfoW();
extern "C" void Thunk_GetRawInputDeviceList();
extern "C" void Thunk_GetSidSubAuthority();
extern "C" void Thunk_GetStartupInfoA();
extern "C" void Thunk_GetStartupInfoW();
extern "C" void Thunk_GetStdHandle();
extern "C" void Thunk_GetStringTypeW();
extern "C" void Thunk_GetSystemDirectoryA();
extern "C" void Thunk_GetSystemInfo();
extern "C" void Thunk_GetSystemMetrics();
extern "C" void Thunk_GetSystemPowerStatus();
extern "C" void Thunk_GetSystemTime();
extern "C" void Thunk_GetSystemTimeAsFileTime();
extern "C" void Thunk_GetTempFileNameW();
extern "C" void Thunk_GetTempPathW();
extern "C" void Thunk_GetThreadContext();
extern "C" void Thunk_GetThreadDesktop();
extern "C" void Thunk_GetThreadPriority();
extern "C" void Thunk_GetTickCount();
extern "C" void Thunk_GetTickCount64();
extern "C" void Thunk_GetTimeZoneInformation();
extern "C" void Thunk_GetTokenInformation();
extern "C" void Thunk_GetUserDefaultLCID();
extern "C" void Thunk_GetUserDefaultLocaleName();
extern "C" void Thunk_GetUserNameA();
extern "C" void Thunk_GetUserObjectInformationA();
extern "C" void Thunk_GetUserObjectInformationW();
extern "C" void Thunk_GetWindowLongA();
extern "C" void Thunk_GetWindowLongPtrA();
extern "C" void Thunk_GetWindowLongPtrW();
extern "C" void Thunk_GetWindowPlacement();
extern "C" void Thunk_GetWindowRect();
extern "C" void Thunk_GetWindowsDirectoryW();
extern "C" void Thunk_GlobalAlloc();
extern "C" void Thunk_GlobalLock();
extern "C" void Thunk_GlobalMemoryStatus();
extern "C" void Thunk_GlobalMemoryStatusEx();
extern "C" void Thunk_GlobalUnlock();
extern "C" void Thunk_HeapAlloc();
extern "C" void Thunk_HeapFree();
extern "C" void Thunk_HeapQueryInformation();
extern "C" void Thunk_HeapReAlloc();
extern "C" void Thunk_HeapSize();
extern "C" void Thunk_HidD_FreePreparsedData();
extern "C" void Thunk_HidD_GetAttributes();
extern "C" void Thunk_HidD_GetHidGuid();
extern "C" void Thunk_HidD_GetManufacturerString();
extern "C" void Thunk_HidD_GetPreparsedData();
extern "C" void Thunk_HidD_GetProductString();
extern "C" void Thunk_HidD_GetSerialNumberString();
extern "C" void Thunk_HidP_GetButtonCaps();
extern "C" void Thunk_HidP_GetCaps();
extern "C" void Thunk_HidP_GetData();
extern "C" void Thunk_HidP_GetValueCaps();
extern "C" void Thunk_HidP_MaxDataListLength();
extern "C" void Thunk_HidP_SetUsageValue();
extern "C" void Thunk_HidP_SetUsages();
extern "C" void Thunk_ImmAssociateContext();
extern "C" void Thunk_ImmAssociateContextEx();
extern "C" void Thunk_ImmGetCompositionStringW();
extern "C" void Thunk_ImmGetContext();
extern "C" void Thunk_ImmGetConversionStatus();
extern "C" void Thunk_ImmNotifyIME();
extern "C" void Thunk_ImmReleaseContext();
extern "C" void Thunk_ImmSetCompositionStringW();
extern "C" void Thunk_InitializeCriticalSection();
extern "C" void Thunk_InitializeCriticalSectionAndSpinCount();
extern "C" void Thunk_InitializeCriticalSectionEx();
extern "C" void Thunk_InitializeSListHead();
extern "C" void Thunk_InterlockedFlushSList();
extern "C" void Thunk_InterlockedPopEntrySList();
extern "C" void Thunk_InterlockedPushEntrySList();
extern "C" void Thunk_IsClipboardFormatAvailable();
extern "C" void Thunk_IsDebuggerPresent();
extern "C" void Thunk_IsDialogMessageW();
extern "C" void Thunk_IsDlgButtonChecked();
extern "C" void Thunk_IsIconic();
extern "C" void Thunk_IsProcessorFeaturePresent();
extern "C" void Thunk_IsValidCodePage();
extern "C" void Thunk_IsValidLocale();
extern "C" void Thunk_IsWindowVisible();
extern "C" void Thunk_KillTimer();
extern "C" void Thunk_LCMapStringW();
extern "C" void Thunk_LeaveCriticalSection();
extern "C" void Thunk_LoadCursorA();
extern "C" void Thunk_LoadIconA();
extern "C" void Thunk_LoadLibraryA();
extern "C" void Thunk_LoadLibraryExW();
extern "C" void Thunk_LoadLibraryW();
extern "C" void Thunk_LocalAlloc();
extern "C" void Thunk_LocalFree();
extern "C" void Thunk_MessageBoxA();
extern "C" void Thunk_MessageBoxW();
extern "C" void Thunk_MonitorFromPoint();
extern "C" void Thunk_MonitorFromRect();
extern "C" void Thunk_MonitorFromWindow();
extern "C" void Thunk_MoveFileExW();
extern "C" void Thunk_MsgWaitForMultipleObjects();
extern "C" void Thunk_MultiByteToWideChar();
extern "C" void Thunk_OffsetRect();
extern "C" void Thunk_OpenClipboard();
extern "C" void Thunk_OpenEventA();
extern "C" void Thunk_OpenProcessToken();
extern "C" void Thunk_OpenThread();
extern "C" void Thunk_OutputDebugStringA();
extern "C" void Thunk_PathCanonicalizeW();
extern "C" void Thunk_PathFileExistsW();
extern "C" void Thunk_PeekMessageA();
extern "C" void Thunk_PeekMessageW();
extern "C" void Thunk_PeekNamedPipe();
extern "C" void Thunk_PostQuitMessage();
extern "C" void Thunk_PropVariantClear();
extern "C" void Thunk_PropVariantCopy();
extern "C" void Thunk_PtInRect();
extern "C" void Thunk_QueryPerformanceCounter();
extern "C" void Thunk_QueryPerformanceFrequency();
extern "C" void Thunk_RaiseException();
extern "C" void Thunk_ReadConsoleInputW();
extern "C" void Thunk_ReadConsoleW();
extern "C" void Thunk_ReadFile();
extern "C" void Thunk_ReadProcessMemory();
extern "C" void Thunk_RegCloseKey();
extern "C" void Thunk_RegCreateKeyExW();
extern "C" void Thunk_RegCreateKeyW();
extern "C" void Thunk_RegDeleteValueA();
extern "C" void Thunk_RegOpenKeyExW();
extern "C" void Thunk_RegQueryValueExA();
extern "C" void Thunk_RegQueryValueExW();
extern "C" void Thunk_RegSetValueExA();
extern "C" void Thunk_RegSetValueExW();
extern "C" void Thunk_RegisterClassExW();
extern "C" void Thunk_RegisterClassW();
extern "C" void Thunk_RegisterDeviceNotificationW();
extern "C" void Thunk_RegisterEventSourceW();
extern "C" void Thunk_RegisterRawInputDevices();
extern "C" void Thunk_RegisterWindowMessageA();
extern "C" void Thunk_ReleaseCapture();
extern "C" void Thunk_ReleaseDC();
extern "C" void Thunk_ReleaseSemaphore();
extern "C" void Thunk_RemoveDirectoryW();
extern "C" void Thunk_ReplaceFileW();
extern "C" void Thunk_ReportEventW();
extern "C" void Thunk_ResetEvent();
extern "C" void Thunk_ResumeThread();
extern "C" void Thunk_RtlCaptureContext();
extern "C" void Thunk_RtlLookupFunctionEntry();
extern "C" void Thunk_RtlPcToFileHeader();
extern "C" void Thunk_RtlUnwindEx();
extern "C" void Thunk_RtlVirtualUnwind();
extern "C" void Thunk_SHDeleteKeyW();
extern "C" void Thunk_SHFileOperationW();
extern "C" void Thunk_SHGetFolderPathW();
extern "C" void Thunk_ScreenToClient();
extern "C" void Thunk_SendDlgItemMessageW();
extern "C" void Thunk_SendMessageA();
extern "C" void Thunk_SendMessageTimeoutA();
extern "C" void Thunk_SendMessageW();
extern "C" void Thunk_SetCapture();
extern "C" void Thunk_SetClipboardData();
extern "C" void Thunk_SetConsoleCtrlHandler();
extern "C" void Thunk_SetConsoleMode();
extern "C" void Thunk_SetCursor();
extern "C" void Thunk_SetCursorPos();
extern "C" void Thunk_SetDlgItemTextA();
extern "C" void Thunk_SetDlgItemTextW();
extern "C" void Thunk_SetDllDirectoryW();
extern "C" void Thunk_SetEndOfFile();
extern "C" void Thunk_SetEnvironmentVariableW();
extern "C" void Thunk_SetErrorMode();
extern "C" void Thunk_SetEvent();
extern "C" void Thunk_SetFileAttributesW();
extern "C" void Thunk_SetFilePointer();
extern "C" void Thunk_SetFilePointerEx();
extern "C" void Thunk_SetFileTime();
extern "C" void Thunk_SetFocus();
extern "C" void Thunk_SetForegroundWindow();
extern "C" void Thunk_SetHandleInformation();
extern "C" void Thunk_SetLastError();
extern "C" void Thunk_SetPixelFormat();
extern "C" void Thunk_SetStdHandle();
extern "C" void Thunk_SetThreadAffinityMask();
extern "C" void Thunk_SetThreadPriority();
extern "C" void Thunk_SetTimer();
extern "C" void Thunk_SetUnhandledExceptionFilter();
extern "C" void Thunk_SetWaitableTimer();
extern "C" void Thunk_SetWindowLongA();
extern "C" void Thunk_SetWindowLongPtrA();
extern "C" void Thunk_SetWindowLongPtrW();
extern "C" void Thunk_SetWindowPos();
extern "C" void Thunk_SetWindowTextW();
extern "C" void Thunk_SetupDiDestroyDeviceInfoList();
extern "C" void Thunk_SetupDiEnumDeviceInfo();
extern "C" void Thunk_SetupDiEnumDeviceInterfaces();
extern "C" void Thunk_SetupDiGetClassDevsA();
extern "C" void Thunk_SetupDiGetDeviceInterfaceDetailW();
extern "C" void Thunk_ShellExecuteW();
extern "C" void Thunk_ShowCursor();
extern "C" void Thunk_ShowWindow();
extern "C" void Thunk_Sleep();
extern "C" void Thunk_SleepEx();
extern "C" void Thunk_StringFromGUID2();
extern "C" void Thunk_SuspendThread();
extern "C" void Thunk_SwapBuffers();
extern "C" void Thunk_SwitchToThread();
extern "C" void Thunk_SysAllocString();
extern "C" void Thunk_SysFreeString();
extern "C" void Thunk_SystemParametersInfoW();
extern "C" void Thunk_SystemTimeToFileTime();
extern "C" void Thunk_SystemTimeToTzSpecificLocalTime();
extern "C" void Thunk_TerminateProcess();
extern "C" void Thunk_Thread32First();
extern "C" void Thunk_Thread32Next();
extern "C" void Thunk_TlsAlloc();
extern "C" void Thunk_TlsFree();
extern "C" void Thunk_TlsGetValue();
extern "C" void Thunk_TlsSetValue();
extern "C" void Thunk_TrackMouseEvent();
extern "C" void Thunk_TranslateMessage();
extern "C" void Thunk_TryEnterCriticalSection();
extern "C" void Thunk_UnhandledExceptionFilter();
extern "C" void Thunk_UnregisterClassW();
extern "C" void Thunk_UnregisterDeviceNotification();
extern "C" void Thunk_UpdateWindow();
extern "C" void Thunk_ValidateRect();
extern "C" void Thunk_VariantChangeType();
extern "C" void Thunk_VariantClear();
extern "C" void Thunk_VariantInit();
extern "C" void Thunk_VerQueryValueA();
extern "C" void Thunk_VerSetConditionMask();
extern "C" void Thunk_VerifyVersionInfoA();
extern "C" void Thunk_VerifyVersionInfoW();
extern "C" void Thunk_VirtualAlloc();
extern "C" void Thunk_VirtualFree();
extern "C" void Thunk_VirtualProtect();
extern "C" void Thunk_WICConvertBitmapSource();
extern "C" void Thunk_WSAAsyncGetHostByName();
extern "C" void Thunk_WSACancelAsyncRequest();
extern "C" void Thunk_WSACleanup();
extern "C" void Thunk_WSACloseEvent();
extern "C" void Thunk_WSACreateEvent();
extern "C" void Thunk_WSAEnumNetworkEvents();
extern "C" void Thunk_WSAEventSelect();
extern "C" void Thunk_WSAGetLastError();
extern "C" void Thunk_WSAIoctl();
extern "C" void Thunk_WSARecvFrom();
extern "C" void Thunk_WSAResetEvent();
extern "C" void Thunk_WSASendDisconnect();
extern "C" void Thunk_WSASetEvent();
extern "C" void Thunk_WSASetLastError();
extern "C" void Thunk_WSASocketA();
extern "C" void Thunk_WSAStartup();
extern "C" void Thunk_WSAWaitForMultipleEvents();
extern "C" void Thunk_WaitForMultipleObjects();
extern "C" void Thunk_WaitForSingleObject();
extern "C" void Thunk_WaitForSingleObjectEx();
extern "C" void Thunk_WideCharToMultiByte();
extern "C" void Thunk_WinHttpGetIEProxyConfigForCurrentUser();
extern "C" void Thunk_WriteConsoleW();
extern "C" void Thunk_WriteFile();
extern "C" void Thunk___WSAFDIsSet();
extern "C" void Thunk_accept();
extern "C" void Thunk_bind();
extern "C" void Thunk_closesocket();
extern "C" void Thunk_connect();
extern "C" void Thunk_freeaddrinfo();
extern "C" void Thunk_getaddrinfo();
extern "C" void Thunk_gethostbyaddr();
extern "C" void Thunk_gethostbyname();
extern "C" void Thunk_gethostname();
extern "C" void Thunk_getnameinfo();
extern "C" void Thunk_getpeername();
extern "C" void Thunk_getprotobyname();
extern "C" void Thunk_getsockname();
extern "C" void Thunk_getsockopt();
extern "C" void Thunk_htonl();
extern "C" void Thunk_htons();
extern "C" void Thunk_inet_addr();
extern "C" void Thunk_ioctlsocket();
extern "C" void Thunk_listen();
extern "C" void Thunk_ntohl();
extern "C" void Thunk_ntohs();
extern "C" void Thunk_recv();
extern "C" void Thunk_recvfrom();
extern "C" void Thunk_select();
extern "C" void Thunk_send();
extern "C" void Thunk_sendto();
extern "C" void Thunk_setsockopt();
extern "C" void Thunk_shutdown();
extern "C" void Thunk_socket();
extern "C" void Thunk_timeBeginPeriod();
extern "C" void Thunk_timeEndPeriod();
extern "C" void Thunk_timeGetTime();
extern "C" void Thunk_waveInAddBuffer();
extern "C" void Thunk_waveInClose();
extern "C" void Thunk_waveInGetDevCapsA();
extern "C" void Thunk_waveInGetDevCapsW();
extern "C" void Thunk_waveInGetNumDevs();
extern "C" void Thunk_waveInOpen();
extern "C" void Thunk_waveInPrepareHeader();
extern "C" void Thunk_waveInReset();
extern "C" void Thunk_waveInStart();
extern "C" void Thunk_waveInUnprepareHeader();
extern "C" void Thunk_waveOutClose();
extern "C" void Thunk_waveOutGetDevCapsA();
extern "C" void Thunk_waveOutGetDevCapsW();
extern "C" void Thunk_waveOutGetNumDevs();
extern "C" void Thunk_waveOutGetPosition();
extern "C" void Thunk_waveOutOpen();
extern "C" void Thunk_waveOutPrepareHeader();
extern "C" void Thunk_waveOutReset();
extern "C" void Thunk_waveOutUnprepareHeader();
extern "C" void Thunk_waveOutWrite();
extern "C" void Thunk_wglCreateContext();
extern "C" void Thunk_wglDeleteContext();
extern "C" void Thunk_wglGetCurrentContext();
extern "C" void Thunk_wglGetCurrentDC();
extern "C" void Thunk_wglGetProcAddress();
extern "C" void Thunk_wglMakeCurrent();

typedef struct {
    const char* name;
    void* thunk_ptr;
} IAT_HOOK_ENTRY;

static const IAT_HOOK_ENTRY g_auto_iat_hooks[] = {
    {"AdjustWindowRectEx", (void*)Thunk_AdjustWindowRectEx},
    {"AllowSetForegroundWindow", (void*)Thunk_AllowSetForegroundWindow},
    {"BCryptGenRandom", (void*)Thunk_BCryptGenRandom},
    {"CancelIo", (void*)Thunk_CancelIo},
    {"CertAddEncodedCertificateToStore", (void*)Thunk_CertAddEncodedCertificateToStore},
    {"CertCloseStore", (void*)Thunk_CertCloseStore},
    {"CertFreeCertificateChain", (void*)Thunk_CertFreeCertificateChain},
    {"CertFreeCertificateContext", (void*)Thunk_CertFreeCertificateContext},
    {"CertGetCertificateChain", (void*)Thunk_CertGetCertificateChain},
    {"CertOpenStore", (void*)Thunk_CertOpenStore},
    {"CertVerifyCertificateChainPolicy", (void*)Thunk_CertVerifyCertificateChainPolicy},
    {"CheckDlgButton", (void*)Thunk_CheckDlgButton},
    {"ChoosePixelFormat", (void*)Thunk_ChoosePixelFormat},
    {"ClientToScreen", (void*)Thunk_ClientToScreen},
    {"ClipCursor", (void*)Thunk_ClipCursor},
    {"CloseClipboard", (void*)Thunk_CloseClipboard},
    {"CloseHandle", (void*)Thunk_CloseHandle},
    {"CoCreateFreeThreadedMarshaler", (void*)Thunk_CoCreateFreeThreadedMarshaler},
    {"CoCreateGuid", (void*)Thunk_CoCreateGuid},
    {"CoCreateInstance", (void*)Thunk_CoCreateInstance},
    {"CoInitialize", (void*)Thunk_CoInitialize},
    {"CoSetProxyBlanket", (void*)Thunk_CoSetProxyBlanket},
    {"CoTaskMemAlloc", (void*)Thunk_CoTaskMemAlloc},
    {"CoTaskMemFree", (void*)Thunk_CoTaskMemFree},
    {"CoUninitialize", (void*)Thunk_CoUninitialize},
    {"CommandLineToArgvW", (void*)Thunk_CommandLineToArgvW},
    {"CompareStringW", (void*)Thunk_CompareStringW},
    {"CopyFileW", (void*)Thunk_CopyFileW},
    {"CopyImage", (void*)Thunk_CopyImage},
    {"CopyRect", (void*)Thunk_CopyRect},
    {"CreateBitmap", (void*)Thunk_CreateBitmap},
    {"CreateDIBSection", (void*)Thunk_CreateDIBSection},
    {"CreateDialogParamA", (void*)Thunk_CreateDialogParamA},
    {"CreateDialogParamW", (void*)Thunk_CreateDialogParamW},
    {"CreateDirectoryW", (void*)Thunk_CreateDirectoryW},
    {"CreateEventA", (void*)Thunk_CreateEventA},
    {"CreateEventW", (void*)Thunk_CreateEventW},
    {"CreateFileA", (void*)Thunk_CreateFileA},
    {"CreateFileW", (void*)Thunk_CreateFileW},
    {"CreateIconIndirect", (void*)Thunk_CreateIconIndirect},
    {"CreateIoCompletionPort", (void*)Thunk_CreateIoCompletionPort},
    {"CreateMutexA", (void*)Thunk_CreateMutexA},
    {"CreatePipe", (void*)Thunk_CreatePipe},
    {"CreateProcessW", (void*)Thunk_CreateProcessW},
    {"CreateSemaphoreW", (void*)Thunk_CreateSemaphoreW},
    {"CreateThread", (void*)Thunk_CreateThread},
    {"CreateToolhelp32Snapshot", (void*)Thunk_CreateToolhelp32Snapshot},
    {"CreateWaitableTimerA", (void*)Thunk_CreateWaitableTimerA},
    {"CreateWindowExW", (void*)Thunk_CreateWindowExW},
    {"CryptAcquireContextA", (void*)Thunk_CryptAcquireContextA},
    {"CryptCreateHash", (void*)Thunk_CryptCreateHash},
    {"CryptDestroyHash", (void*)Thunk_CryptDestroyHash},
    {"CryptDestroyKey", (void*)Thunk_CryptDestroyKey},
    {"CryptEncrypt", (void*)Thunk_CryptEncrypt},
    {"CryptGenRandom", (void*)Thunk_CryptGenRandom},
    {"CryptGetHashParam", (void*)Thunk_CryptGetHashParam},
    {"CryptHashData", (void*)Thunk_CryptHashData},
    {"CryptImportKey", (void*)Thunk_CryptImportKey},
    {"CryptReleaseContext", (void*)Thunk_CryptReleaseContext},
    {"DebugBreak", (void*)Thunk_DebugBreak},
    {"DecodePointer", (void*)Thunk_DecodePointer},
    {"DefWindowProcW", (void*)Thunk_DefWindowProcW},
    {"DeleteCriticalSection", (void*)Thunk_DeleteCriticalSection},
    {"DeleteFileW", (void*)Thunk_DeleteFileW},
    {"DeleteObject", (void*)Thunk_DeleteObject},
    {"DeregisterEventSource", (void*)Thunk_DeregisterEventSource},
    {"DestroyCursor", (void*)Thunk_DestroyCursor},
    {"DestroyIcon", (void*)Thunk_DestroyIcon},
    {"DestroyWindow", (void*)Thunk_DestroyWindow},
    {"DialogBoxParamA", (void*)Thunk_DialogBoxParamA},
    {"DialogBoxParamW", (void*)Thunk_DialogBoxParamW},
    {"DispatchMessageA", (void*)Thunk_DispatchMessageA},
    {"DispatchMessageW", (void*)Thunk_DispatchMessageW},
    {"DragDetect", (void*)Thunk_DragDetect},
    {"DuplicateHandle", (void*)Thunk_DuplicateHandle},
    {"DwmGetWindowAttribute", (void*)Thunk_DwmGetWindowAttribute},
    {"EmptyClipboard", (void*)Thunk_EmptyClipboard},
    {"EnableWindow", (void*)Thunk_EnableWindow},
    {"EncodePointer", (void*)Thunk_EncodePointer},
    {"EndDialog", (void*)Thunk_EndDialog},
    {"EnterCriticalSection", (void*)Thunk_EnterCriticalSection},
    {"EnumDisplayDevicesA", (void*)Thunk_EnumDisplayDevicesA},
    {"EnumDisplayMonitors", (void*)Thunk_EnumDisplayMonitors},
    {"EnumDisplaySettingsA", (void*)Thunk_EnumDisplaySettingsA},
    {"EnumDisplaySettingsW", (void*)Thunk_EnumDisplaySettingsW},
    {"EnumSystemLocalesW", (void*)Thunk_EnumSystemLocalesW},
    {"EnumWindows", (void*)Thunk_EnumWindows},
    {"ExitProcess", (void*)Thunk_ExitProcess},
    {"ExitThread", (void*)Thunk_ExitThread},
    {"ExpandEnvironmentStringsA", (void*)Thunk_ExpandEnvironmentStringsA},
    {"ExpandEnvironmentStringsW", (void*)Thunk_ExpandEnvironmentStringsW},
    {"FileTimeToSystemTime", (void*)Thunk_FileTimeToSystemTime},
    {"FindClose", (void*)Thunk_FindClose},
    {"FindFirstFileExW", (void*)Thunk_FindFirstFileExW},
    {"FindFirstFileW", (void*)Thunk_FindFirstFileW},
    {"FindNextFileW", (void*)Thunk_FindNextFileW},
    {"FlushConsoleInputBuffer", (void*)Thunk_FlushConsoleInputBuffer},
    {"FlushFileBuffers", (void*)Thunk_FlushFileBuffers},
    {"FormatMessageA", (void*)Thunk_FormatMessageA},
    {"FormatMessageW", (void*)Thunk_FormatMessageW},
    {"FreeEnvironmentStringsW", (void*)Thunk_FreeEnvironmentStringsW},
    {"FreeLibrary", (void*)Thunk_FreeLibrary},
    {"FreeLibraryAndExitThread", (void*)Thunk_FreeLibraryAndExitThread},
    {"GetACP", (void*)Thunk_GetACP},
    {"GetActiveWindow", (void*)Thunk_GetActiveWindow},
    {"GetAncestor", (void*)Thunk_GetAncestor},
    {"GetAsyncKeyState", (void*)Thunk_GetAsyncKeyState},
    {"GetCPInfo", (void*)Thunk_GetCPInfo},
    {"GetCaretBlinkTime", (void*)Thunk_GetCaretBlinkTime},
    {"GetClientRect", (void*)Thunk_GetClientRect},
    {"GetClipboardData", (void*)Thunk_GetClipboardData},
    {"GetCommandLineA", (void*)Thunk_GetCommandLineA},
    {"GetCommandLineW", (void*)Thunk_GetCommandLineW},
    {"GetComputerNameW", (void*)Thunk_GetComputerNameW},
    {"GetConsoleCP", (void*)Thunk_GetConsoleCP},
    {"GetConsoleMode", (void*)Thunk_GetConsoleMode},
    {"GetCurrentDirectoryA", (void*)Thunk_GetCurrentDirectoryA},
    {"GetCurrentDirectoryW", (void*)Thunk_GetCurrentDirectoryW},
    {"GetCurrentProcess", (void*)Thunk_GetCurrentProcess},
    {"GetCurrentProcessId", (void*)Thunk_GetCurrentProcessId},
    {"GetCurrentThread", (void*)Thunk_GetCurrentThread},
    {"GetCurrentThreadId", (void*)Thunk_GetCurrentThreadId},
    {"GetCursorPos", (void*)Thunk_GetCursorPos},
    {"GetDC", (void*)Thunk_GetDC},
    {"GetDesktopWindow", (void*)Thunk_GetDesktopWindow},
    {"GetDeviceCaps", (void*)Thunk_GetDeviceCaps},
    {"GetDiskFreeSpaceExW", (void*)Thunk_GetDiskFreeSpaceExW},
    {"GetDlgItem", (void*)Thunk_GetDlgItem},
    {"GetDriveTypeW", (void*)Thunk_GetDriveTypeW},
    {"GetEnvironmentStringsW", (void*)Thunk_GetEnvironmentStringsW},
    {"GetEnvironmentVariableA", (void*)Thunk_GetEnvironmentVariableA},
    {"GetExitCodeProcess", (void*)Thunk_GetExitCodeProcess},
    {"GetFileAttributesA", (void*)Thunk_GetFileAttributesA},
    {"GetFileAttributesExW", (void*)Thunk_GetFileAttributesExW},
    {"GetFileAttributesW", (void*)Thunk_GetFileAttributesW},
    {"GetFileInformationByHandle", (void*)Thunk_GetFileInformationByHandle},
    {"GetFileSize", (void*)Thunk_GetFileSize},
    {"GetFileType", (void*)Thunk_GetFileType},
    {"GetFileVersionInfoA", (void*)Thunk_GetFileVersionInfoA},
    {"GetFileVersionInfoSizeA", (void*)Thunk_GetFileVersionInfoSizeA},
    {"GetFocus", (void*)Thunk_GetFocus},
    {"GetFullPathNameW", (void*)Thunk_GetFullPathNameW},
    {"GetKeyNameTextW", (void*)Thunk_GetKeyNameTextW},
    {"GetKeyState", (void*)Thunk_GetKeyState},
    {"GetKeyboardLayoutNameW", (void*)Thunk_GetKeyboardLayoutNameW},
    {"GetLastError", (void*)Thunk_GetLastError},
    {"GetLocalTime", (void*)Thunk_GetLocalTime},
    {"GetLocaleInfoW", (void*)Thunk_GetLocaleInfoW},
    {"GetMessageA", (void*)Thunk_GetMessageA},
    {"GetMessageExtraInfo", (void*)Thunk_GetMessageExtraInfo},
    {"GetMessagePos", (void*)Thunk_GetMessagePos},
    {"GetMessageTime", (void*)Thunk_GetMessageTime},
    {"GetModuleFileNameA", (void*)Thunk_GetModuleFileNameA},
    {"GetModuleFileNameW", (void*)Thunk_GetModuleFileNameW},
    {"GetModuleHandleA", (void*)Thunk_GetModuleHandleA},
    {"GetModuleHandleExW", (void*)Thunk_GetModuleHandleExW},
    {"GetModuleHandleW", (void*)Thunk_GetModuleHandleW},
    {"GetMonitorInfoA", (void*)Thunk_GetMonitorInfoA},
    {"GetMonitorInfoW", (void*)Thunk_GetMonitorInfoW},
    {"GetOEMCP", (void*)Thunk_GetOEMCP},
    {"GetObjectA", (void*)Thunk_GetObjectA},
    {"GetOverlappedResult", (void*)Thunk_GetOverlappedResult},
    {"GetParent", (void*)Thunk_GetParent},
    {"GetProcAddress", (void*)Thunk_GetProcAddress},
    {"GetProcessHeap", (void*)Thunk_GetProcessHeap},
    {"GetProcessId", (void*)Thunk_GetProcessId},
    {"GetProcessWindowStation", (void*)Thunk_GetProcessWindowStation},
    {"GetQueuedCompletionStatus", (void*)Thunk_GetQueuedCompletionStatus},
    {"GetRawInputData", (void*)Thunk_GetRawInputData},
    {"GetRawInputDeviceInfoW", (void*)Thunk_GetRawInputDeviceInfoW},
    {"GetRawInputDeviceList", (void*)Thunk_GetRawInputDeviceList},
    {"GetSidSubAuthority", (void*)Thunk_GetSidSubAuthority},
    {"GetStartupInfoA", (void*)Thunk_GetStartupInfoA},
    {"GetStartupInfoW", (void*)Thunk_GetStartupInfoW},
    {"GetStdHandle", (void*)Thunk_GetStdHandle},
    {"GetStringTypeW", (void*)Thunk_GetStringTypeW},
    {"GetSystemDirectoryA", (void*)Thunk_GetSystemDirectoryA},
    {"GetSystemInfo", (void*)Thunk_GetSystemInfo},
    {"GetSystemMetrics", (void*)Thunk_GetSystemMetrics},
    {"GetSystemPowerStatus", (void*)Thunk_GetSystemPowerStatus},
    {"GetSystemTime", (void*)Thunk_GetSystemTime},
    {"GetSystemTimeAsFileTime", (void*)Thunk_GetSystemTimeAsFileTime},
    {"GetTempFileNameW", (void*)Thunk_GetTempFileNameW},
    {"GetTempPathW", (void*)Thunk_GetTempPathW},
    {"GetThreadContext", (void*)Thunk_GetThreadContext},
    {"GetThreadDesktop", (void*)Thunk_GetThreadDesktop},
    {"GetThreadPriority", (void*)Thunk_GetThreadPriority},
    {"GetTickCount", (void*)Thunk_GetTickCount},
    {"GetTickCount64", (void*)Thunk_GetTickCount64},
    {"GetTimeZoneInformation", (void*)Thunk_GetTimeZoneInformation},
    {"GetTokenInformation", (void*)Thunk_GetTokenInformation},
    {"GetUserDefaultLCID", (void*)Thunk_GetUserDefaultLCID},
    {"GetUserDefaultLocaleName", (void*)Thunk_GetUserDefaultLocaleName},
    {"GetUserNameA", (void*)Thunk_GetUserNameA},
    {"GetUserObjectInformationA", (void*)Thunk_GetUserObjectInformationA},
    {"GetUserObjectInformationW", (void*)Thunk_GetUserObjectInformationW},
    {"GetWindowLongA", (void*)Thunk_GetWindowLongA},
    {"GetWindowLongPtrA", (void*)Thunk_GetWindowLongPtrA},
    {"GetWindowLongPtrW", (void*)Thunk_GetWindowLongPtrW},
    {"GetWindowPlacement", (void*)Thunk_GetWindowPlacement},
    {"GetWindowRect", (void*)Thunk_GetWindowRect},
    {"GetWindowsDirectoryW", (void*)Thunk_GetWindowsDirectoryW},
    {"GlobalAlloc", (void*)Thunk_GlobalAlloc},
    {"GlobalLock", (void*)Thunk_GlobalLock},
    {"GlobalMemoryStatus", (void*)Thunk_GlobalMemoryStatus},
    {"GlobalMemoryStatusEx", (void*)Thunk_GlobalMemoryStatusEx},
    {"GlobalUnlock", (void*)Thunk_GlobalUnlock},
    {"HeapAlloc", (void*)Thunk_HeapAlloc},
    {"HeapFree", (void*)Thunk_HeapFree},
    {"HeapQueryInformation", (void*)Thunk_HeapQueryInformation},
    {"HeapReAlloc", (void*)Thunk_HeapReAlloc},
    {"HeapSize", (void*)Thunk_HeapSize},
    {"HidD_FreePreparsedData", (void*)Thunk_HidD_FreePreparsedData},
    {"HidD_GetAttributes", (void*)Thunk_HidD_GetAttributes},
    {"HidD_GetHidGuid", (void*)Thunk_HidD_GetHidGuid},
    {"HidD_GetManufacturerString", (void*)Thunk_HidD_GetManufacturerString},
    {"HidD_GetPreparsedData", (void*)Thunk_HidD_GetPreparsedData},
    {"HidD_GetProductString", (void*)Thunk_HidD_GetProductString},
    {"HidD_GetSerialNumberString", (void*)Thunk_HidD_GetSerialNumberString},
    {"HidP_GetButtonCaps", (void*)Thunk_HidP_GetButtonCaps},
    {"HidP_GetCaps", (void*)Thunk_HidP_GetCaps},
    {"HidP_GetData", (void*)Thunk_HidP_GetData},
    {"HidP_GetValueCaps", (void*)Thunk_HidP_GetValueCaps},
    {"HidP_MaxDataListLength", (void*)Thunk_HidP_MaxDataListLength},
    {"HidP_SetUsageValue", (void*)Thunk_HidP_SetUsageValue},
    {"HidP_SetUsages", (void*)Thunk_HidP_SetUsages},
    {"ImmAssociateContext", (void*)Thunk_ImmAssociateContext},
    {"ImmAssociateContextEx", (void*)Thunk_ImmAssociateContextEx},
    {"ImmGetCompositionStringW", (void*)Thunk_ImmGetCompositionStringW},
    {"ImmGetContext", (void*)Thunk_ImmGetContext},
    {"ImmGetConversionStatus", (void*)Thunk_ImmGetConversionStatus},
    {"ImmNotifyIME", (void*)Thunk_ImmNotifyIME},
    {"ImmReleaseContext", (void*)Thunk_ImmReleaseContext},
    {"ImmSetCompositionStringW", (void*)Thunk_ImmSetCompositionStringW},
    {"InitializeCriticalSection", (void*)Thunk_InitializeCriticalSection},
    {"InitializeCriticalSectionAndSpinCount", (void*)Thunk_InitializeCriticalSectionAndSpinCount},
    {"InitializeCriticalSectionEx", (void*)Thunk_InitializeCriticalSectionEx},
    {"InitializeSListHead", (void*)Thunk_InitializeSListHead},
    {"InterlockedFlushSList", (void*)Thunk_InterlockedFlushSList},
    {"InterlockedPopEntrySList", (void*)Thunk_InterlockedPopEntrySList},
    {"InterlockedPushEntrySList", (void*)Thunk_InterlockedPushEntrySList},
    {"IsClipboardFormatAvailable", (void*)Thunk_IsClipboardFormatAvailable},
    {"IsDebuggerPresent", (void*)Thunk_IsDebuggerPresent},
    {"IsDialogMessageW", (void*)Thunk_IsDialogMessageW},
    {"IsDlgButtonChecked", (void*)Thunk_IsDlgButtonChecked},
    {"IsIconic", (void*)Thunk_IsIconic},
    {"IsProcessorFeaturePresent", (void*)Thunk_IsProcessorFeaturePresent},
    {"IsValidCodePage", (void*)Thunk_IsValidCodePage},
    {"IsValidLocale", (void*)Thunk_IsValidLocale},
    {"IsWindowVisible", (void*)Thunk_IsWindowVisible},
    {"KillTimer", (void*)Thunk_KillTimer},
    {"LCMapStringW", (void*)Thunk_LCMapStringW},
    {"LeaveCriticalSection", (void*)Thunk_LeaveCriticalSection},
    {"LoadCursorA", (void*)Thunk_LoadCursorA},
    {"LoadIconA", (void*)Thunk_LoadIconA},
    {"LoadLibraryA", (void*)Thunk_LoadLibraryA},
    {"LoadLibraryExW", (void*)Thunk_LoadLibraryExW},
    {"LoadLibraryW", (void*)Thunk_LoadLibraryW},
    {"LocalAlloc", (void*)Thunk_LocalAlloc},
    {"LocalFree", (void*)Thunk_LocalFree},
    {"MessageBoxA", (void*)Thunk_MessageBoxA},
    {"MessageBoxW", (void*)Thunk_MessageBoxW},
    {"MonitorFromPoint", (void*)Thunk_MonitorFromPoint},
    {"MonitorFromRect", (void*)Thunk_MonitorFromRect},
    {"MonitorFromWindow", (void*)Thunk_MonitorFromWindow},
    {"MoveFileExW", (void*)Thunk_MoveFileExW},
    {"MsgWaitForMultipleObjects", (void*)Thunk_MsgWaitForMultipleObjects},
    {"MultiByteToWideChar", (void*)Thunk_MultiByteToWideChar},
    {"OffsetRect", (void*)Thunk_OffsetRect},
    {"OpenClipboard", (void*)Thunk_OpenClipboard},
    {"OpenEventA", (void*)Thunk_OpenEventA},
    {"OpenProcessToken", (void*)Thunk_OpenProcessToken},
    {"OpenThread", (void*)Thunk_OpenThread},
    {"OutputDebugStringA", (void*)Thunk_OutputDebugStringA},
    {"PathCanonicalizeW", (void*)Thunk_PathCanonicalizeW},
    {"PathFileExistsW", (void*)Thunk_PathFileExistsW},
    {"PeekMessageA", (void*)Thunk_PeekMessageA},
    {"PeekMessageW", (void*)Thunk_PeekMessageW},
    {"PeekNamedPipe", (void*)Thunk_PeekNamedPipe},
    {"PostQuitMessage", (void*)Thunk_PostQuitMessage},
    {"PropVariantClear", (void*)Thunk_PropVariantClear},
    {"PropVariantCopy", (void*)Thunk_PropVariantCopy},
    {"PtInRect", (void*)Thunk_PtInRect},
    {"QueryPerformanceCounter", (void*)Thunk_QueryPerformanceCounter},
    {"QueryPerformanceFrequency", (void*)Thunk_QueryPerformanceFrequency},
    {"RaiseException", (void*)Thunk_RaiseException},
    {"ReadConsoleInputW", (void*)Thunk_ReadConsoleInputW},
    {"ReadConsoleW", (void*)Thunk_ReadConsoleW},
    {"ReadFile", (void*)Thunk_ReadFile},
    {"ReadProcessMemory", (void*)Thunk_ReadProcessMemory},
    {"RegCloseKey", (void*)Thunk_RegCloseKey},
    {"RegCreateKeyExW", (void*)Thunk_RegCreateKeyExW},
    {"RegCreateKeyW", (void*)Thunk_RegCreateKeyW},
    {"RegDeleteValueA", (void*)Thunk_RegDeleteValueA},
    {"RegOpenKeyExW", (void*)Thunk_RegOpenKeyExW},
    {"RegQueryValueExA", (void*)Thunk_RegQueryValueExA},
    {"RegQueryValueExW", (void*)Thunk_RegQueryValueExW},
    {"RegSetValueExA", (void*)Thunk_RegSetValueExA},
    {"RegSetValueExW", (void*)Thunk_RegSetValueExW},
    {"RegisterClassExW", (void*)Thunk_RegisterClassExW},
    {"RegisterClassW", (void*)Thunk_RegisterClassW},
    {"RegisterDeviceNotificationW", (void*)Thunk_RegisterDeviceNotificationW},
    {"RegisterEventSourceW", (void*)Thunk_RegisterEventSourceW},
    {"RegisterRawInputDevices", (void*)Thunk_RegisterRawInputDevices},
    {"RegisterWindowMessageA", (void*)Thunk_RegisterWindowMessageA},
    {"ReleaseCapture", (void*)Thunk_ReleaseCapture},
    {"ReleaseDC", (void*)Thunk_ReleaseDC},
    {"ReleaseSemaphore", (void*)Thunk_ReleaseSemaphore},
    {"RemoveDirectoryW", (void*)Thunk_RemoveDirectoryW},
    {"ReplaceFileW", (void*)Thunk_ReplaceFileW},
    {"ReportEventW", (void*)Thunk_ReportEventW},
    {"ResetEvent", (void*)Thunk_ResetEvent},
    {"ResumeThread", (void*)Thunk_ResumeThread},
    {"RtlCaptureContext", (void*)Thunk_RtlCaptureContext},
    {"RtlLookupFunctionEntry", (void*)Thunk_RtlLookupFunctionEntry},
    {"RtlPcToFileHeader", (void*)Thunk_RtlPcToFileHeader},
    {"RtlUnwindEx", (void*)Thunk_RtlUnwindEx},
    {"RtlVirtualUnwind", (void*)Thunk_RtlVirtualUnwind},
    {"SHDeleteKeyW", (void*)Thunk_SHDeleteKeyW},
    {"SHFileOperationW", (void*)Thunk_SHFileOperationW},
    {"SHGetFolderPathW", (void*)Thunk_SHGetFolderPathW},
    {"ScreenToClient", (void*)Thunk_ScreenToClient},
    {"SendDlgItemMessageW", (void*)Thunk_SendDlgItemMessageW},
    {"SendMessageA", (void*)Thunk_SendMessageA},
    {"SendMessageTimeoutA", (void*)Thunk_SendMessageTimeoutA},
    {"SendMessageW", (void*)Thunk_SendMessageW},
    {"SetCapture", (void*)Thunk_SetCapture},
    {"SetClipboardData", (void*)Thunk_SetClipboardData},
    {"SetConsoleCtrlHandler", (void*)Thunk_SetConsoleCtrlHandler},
    {"SetConsoleMode", (void*)Thunk_SetConsoleMode},
    {"SetCursor", (void*)Thunk_SetCursor},
    {"SetCursorPos", (void*)Thunk_SetCursorPos},
    {"SetDlgItemTextA", (void*)Thunk_SetDlgItemTextA},
    {"SetDlgItemTextW", (void*)Thunk_SetDlgItemTextW},
    {"SetDllDirectoryW", (void*)Thunk_SetDllDirectoryW},
    {"SetEndOfFile", (void*)Thunk_SetEndOfFile},
    {"SetEnvironmentVariableW", (void*)Thunk_SetEnvironmentVariableW},
    {"SetErrorMode", (void*)Thunk_SetErrorMode},
    {"SetEvent", (void*)Thunk_SetEvent},
    {"SetFileAttributesW", (void*)Thunk_SetFileAttributesW},
    {"SetFilePointer", (void*)Thunk_SetFilePointer},
    {"SetFilePointerEx", (void*)Thunk_SetFilePointerEx},
    {"SetFileTime", (void*)Thunk_SetFileTime},
    {"SetFocus", (void*)Thunk_SetFocus},
    {"SetForegroundWindow", (void*)Thunk_SetForegroundWindow},
    {"SetHandleInformation", (void*)Thunk_SetHandleInformation},
    {"SetLastError", (void*)Thunk_SetLastError},
    {"SetPixelFormat", (void*)Thunk_SetPixelFormat},
    {"SetStdHandle", (void*)Thunk_SetStdHandle},
    {"SetThreadAffinityMask", (void*)Thunk_SetThreadAffinityMask},
    {"SetThreadPriority", (void*)Thunk_SetThreadPriority},
    {"SetTimer", (void*)Thunk_SetTimer},
    {"SetUnhandledExceptionFilter", (void*)Thunk_SetUnhandledExceptionFilter},
    {"SetWaitableTimer", (void*)Thunk_SetWaitableTimer},
    {"SetWindowLongA", (void*)Thunk_SetWindowLongA},
    {"SetWindowLongPtrA", (void*)Thunk_SetWindowLongPtrA},
    {"SetWindowLongPtrW", (void*)Thunk_SetWindowLongPtrW},
    {"SetWindowPos", (void*)Thunk_SetWindowPos},
    {"SetWindowTextW", (void*)Thunk_SetWindowTextW},
    {"SetupDiDestroyDeviceInfoList", (void*)Thunk_SetupDiDestroyDeviceInfoList},
    {"SetupDiEnumDeviceInfo", (void*)Thunk_SetupDiEnumDeviceInfo},
    {"SetupDiEnumDeviceInterfaces", (void*)Thunk_SetupDiEnumDeviceInterfaces},
    {"SetupDiGetClassDevsA", (void*)Thunk_SetupDiGetClassDevsA},
    {"SetupDiGetDeviceInterfaceDetailW", (void*)Thunk_SetupDiGetDeviceInterfaceDetailW},
    {"ShellExecuteW", (void*)Thunk_ShellExecuteW},
    {"ShowCursor", (void*)Thunk_ShowCursor},
    {"ShowWindow", (void*)Thunk_ShowWindow},
    {"Sleep", (void*)Thunk_Sleep},
    {"SleepEx", (void*)Thunk_SleepEx},
    {"StringFromGUID2", (void*)Thunk_StringFromGUID2},
    {"SuspendThread", (void*)Thunk_SuspendThread},
    {"SwapBuffers", (void*)Thunk_SwapBuffers},
    {"SwitchToThread", (void*)Thunk_SwitchToThread},
    {"SysAllocString", (void*)Thunk_SysAllocString},
    {"SysFreeString", (void*)Thunk_SysFreeString},
    {"SystemParametersInfoW", (void*)Thunk_SystemParametersInfoW},
    {"SystemTimeToFileTime", (void*)Thunk_SystemTimeToFileTime},
    {"SystemTimeToTzSpecificLocalTime", (void*)Thunk_SystemTimeToTzSpecificLocalTime},
    {"TerminateProcess", (void*)Thunk_TerminateProcess},
    {"Thread32First", (void*)Thunk_Thread32First},
    {"Thread32Next", (void*)Thunk_Thread32Next},
    {"TlsAlloc", (void*)Thunk_TlsAlloc},
    {"TlsFree", (void*)Thunk_TlsFree},
    {"TlsGetValue", (void*)Thunk_TlsGetValue},
    {"TlsSetValue", (void*)Thunk_TlsSetValue},
    {"TrackMouseEvent", (void*)Thunk_TrackMouseEvent},
    {"TranslateMessage", (void*)Thunk_TranslateMessage},
    {"TryEnterCriticalSection", (void*)Thunk_TryEnterCriticalSection},
    {"UnhandledExceptionFilter", (void*)Thunk_UnhandledExceptionFilter},
    {"UnregisterClassW", (void*)Thunk_UnregisterClassW},
    {"UnregisterDeviceNotification", (void*)Thunk_UnregisterDeviceNotification},
    {"UpdateWindow", (void*)Thunk_UpdateWindow},
    {"ValidateRect", (void*)Thunk_ValidateRect},
    {"VariantChangeType", (void*)Thunk_VariantChangeType},
    {"VariantClear", (void*)Thunk_VariantClear},
    {"VariantInit", (void*)Thunk_VariantInit},
    {"VerQueryValueA", (void*)Thunk_VerQueryValueA},
    {"VerSetConditionMask", (void*)Thunk_VerSetConditionMask},
    {"VerifyVersionInfoA", (void*)Thunk_VerifyVersionInfoA},
    {"VerifyVersionInfoW", (void*)Thunk_VerifyVersionInfoW},
    {"VirtualAlloc", (void*)Thunk_VirtualAlloc},
    {"VirtualFree", (void*)Thunk_VirtualFree},
    {"VirtualProtect", (void*)Thunk_VirtualProtect},
    {"WICConvertBitmapSource", (void*)Thunk_WICConvertBitmapSource},
    {"WSAAsyncGetHostByName", (void*)Thunk_WSAAsyncGetHostByName},
    {"WSACancelAsyncRequest", (void*)Thunk_WSACancelAsyncRequest},
    {"WSACleanup", (void*)Thunk_WSACleanup},
    {"WSACloseEvent", (void*)Thunk_WSACloseEvent},
    {"WSACreateEvent", (void*)Thunk_WSACreateEvent},
    {"WSAEnumNetworkEvents", (void*)Thunk_WSAEnumNetworkEvents},
    {"WSAEventSelect", (void*)Thunk_WSAEventSelect},
    {"WSAGetLastError", (void*)Thunk_WSAGetLastError},
    {"WSAIoctl", (void*)Thunk_WSAIoctl},
    {"WSARecvFrom", (void*)Thunk_WSARecvFrom},
    {"WSAResetEvent", (void*)Thunk_WSAResetEvent},
    {"WSASendDisconnect", (void*)Thunk_WSASendDisconnect},
    {"WSASetEvent", (void*)Thunk_WSASetEvent},
    {"WSASetLastError", (void*)Thunk_WSASetLastError},
    {"WSASocketA", (void*)Thunk_WSASocketA},
    {"WSAStartup", (void*)Thunk_WSAStartup},
    {"WSAWaitForMultipleEvents", (void*)Thunk_WSAWaitForMultipleEvents},
    {"WaitForMultipleObjects", (void*)Thunk_WaitForMultipleObjects},
    {"WaitForSingleObject", (void*)Thunk_WaitForSingleObject},
    {"WaitForSingleObjectEx", (void*)Thunk_WaitForSingleObjectEx},
    {"WideCharToMultiByte", (void*)Thunk_WideCharToMultiByte},
    {"WinHttpGetIEProxyConfigForCurrentUser", (void*)Thunk_WinHttpGetIEProxyConfigForCurrentUser},
    {"WriteConsoleW", (void*)Thunk_WriteConsoleW},
    {"WriteFile", (void*)Thunk_WriteFile},
    {"__WSAFDIsSet", (void*)Thunk___WSAFDIsSet},
    {"accept", (void*)Thunk_accept},
    {"bind", (void*)Thunk_bind},
    {"closesocket", (void*)Thunk_closesocket},
    {"connect", (void*)Thunk_connect},
    {"freeaddrinfo", (void*)Thunk_freeaddrinfo},
    {"getaddrinfo", (void*)Thunk_getaddrinfo},
    {"gethostbyaddr", (void*)Thunk_gethostbyaddr},
    {"gethostbyname", (void*)Thunk_gethostbyname},
    {"gethostname", (void*)Thunk_gethostname},
    {"getnameinfo", (void*)Thunk_getnameinfo},
    {"getpeername", (void*)Thunk_getpeername},
    {"getprotobyname", (void*)Thunk_getprotobyname},
    {"getsockname", (void*)Thunk_getsockname},
    {"getsockopt", (void*)Thunk_getsockopt},
    {"htonl", (void*)Thunk_htonl},
    {"htons", (void*)Thunk_htons},
    {"inet_addr", (void*)Thunk_inet_addr},
    {"ioctlsocket", (void*)Thunk_ioctlsocket},
    {"listen", (void*)Thunk_listen},
    {"ntohl", (void*)Thunk_ntohl},
    {"ntohs", (void*)Thunk_ntohs},
    {"recv", (void*)Thunk_recv},
    {"recvfrom", (void*)Thunk_recvfrom},
    {"select", (void*)Thunk_select},
    {"send", (void*)Thunk_send},
    {"sendto", (void*)Thunk_sendto},
    {"setsockopt", (void*)Thunk_setsockopt},
    {"shutdown", (void*)Thunk_shutdown},
    {"socket", (void*)Thunk_socket},
    {"timeBeginPeriod", (void*)Thunk_timeBeginPeriod},
    {"timeEndPeriod", (void*)Thunk_timeEndPeriod},
    {"timeGetTime", (void*)Thunk_timeGetTime},
    {"waveInAddBuffer", (void*)Thunk_waveInAddBuffer},
    {"waveInClose", (void*)Thunk_waveInClose},
    {"waveInGetDevCapsA", (void*)Thunk_waveInGetDevCapsA},
    {"waveInGetDevCapsW", (void*)Thunk_waveInGetDevCapsW},
    {"waveInGetNumDevs", (void*)Thunk_waveInGetNumDevs},
    {"waveInOpen", (void*)Thunk_waveInOpen},
    {"waveInPrepareHeader", (void*)Thunk_waveInPrepareHeader},
    {"waveInReset", (void*)Thunk_waveInReset},
    {"waveInStart", (void*)Thunk_waveInStart},
    {"waveInUnprepareHeader", (void*)Thunk_waveInUnprepareHeader},
    {"waveOutClose", (void*)Thunk_waveOutClose},
    {"waveOutGetDevCapsA", (void*)Thunk_waveOutGetDevCapsA},
    {"waveOutGetDevCapsW", (void*)Thunk_waveOutGetDevCapsW},
    {"waveOutGetNumDevs", (void*)Thunk_waveOutGetNumDevs},
    {"waveOutGetPosition", (void*)Thunk_waveOutGetPosition},
    {"waveOutOpen", (void*)Thunk_waveOutOpen},
    {"waveOutPrepareHeader", (void*)Thunk_waveOutPrepareHeader},
    {"waveOutReset", (void*)Thunk_waveOutReset},
    {"waveOutUnprepareHeader", (void*)Thunk_waveOutUnprepareHeader},
    {"waveOutWrite", (void*)Thunk_waveOutWrite},
    {"wglCreateContext", (void*)Thunk_wglCreateContext},
    {"wglDeleteContext", (void*)Thunk_wglDeleteContext},
    {"wglGetCurrentContext", (void*)Thunk_wglGetCurrentContext},
    {"wglGetCurrentDC", (void*)Thunk_wglGetCurrentDC},
    {"wglGetProcAddress", (void*)Thunk_wglGetProcAddress},
    {"wglMakeCurrent", (void*)Thunk_wglMakeCurrent},
    {0, 0}
};

#endif // AUTOGEN_STUBS_H
