#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
File: UnityPlayerScan.py
Description: Scan PE Imports and generate C/C++ stubs for Linux Loader.
"""

import sys
import pefile

def generate_stubs(dll_path):
    print(f"[*] Analyzing: {dll_path}")
    try:
        pe = pefile.PE(dll_path)
    except Exception as e:
        print(f"[-] Failed to load PE: {e}")
        return

    if not hasattr(pe, 'DIRECTORY_ENTRY_IMPORT'):
        print("[-] No imports found.")
        return

    imported_funcs = set()
    for entry in pe.DIRECTORY_ENTRY_IMPORT:
        for imp in entry.imports:
            if imp.name is not None:
                imported_funcs.add(imp.name.decode('ascii'))
            else:
                # Handle Ordinals
                imported_funcs.add(f"Ordinal_{imp.ordinal}")

    func_list = sorted(list(imported_funcs))
    print(f"[+] Found {len(func_list)} unique imported functions.")

    # 1. Generate Header (.h)
    with open("autogen_stubs.h", "w") as fh:
        fh.write("// AUTO-GENERATED BY UnityPlayerScan.py\n")
        fh.write("#ifndef AUTOGEN_STUBS_H\n")
        fh.write("#define AUTOGEN_STUBS_H\n\n")
        fh.write("#include <stdint.h>\n\n")
        
        for func in func_list:
            fh.write(f"extern \"C\" void Thunk_{func}();\n")
            
        fh.write("\ntypedef struct {\n")
        fh.write("    const char* name;\n")
        fh.write("    void* thunk_ptr;\n")
        fh.write("} IAT_HOOK_ENTRY;\n\n")
        
        fh.write("static const IAT_HOOK_ENTRY g_auto_iat_hooks[] = {\n")
        for func in func_list:
            fh.write(f"    {{\"{func}\", (void*)Thunk_{func}}},\n")
        fh.write("    {0, 0}\n") # Terminator
        fh.write("};\n\n")
        fh.write("#endif // AUTOGEN_STUBS_H\n")

    # 2. Generate Assembly (.S)
    with open("autogen_stubs.S", "w") as fs:
        fs.write("// AUTO-GENERATED BY UnityPlayerScan.py\n")
        fs.write(".text\n")
        fs.write(".extern FatalMissingAPI\n\n")
        
        for func in func_list:
            fs.write(f".global Thunk_{func}\n")
            fs.write(f"Thunk_{func}:\n")
            # Move the address of the string into rdi (Arg 1 for SysV)
            fs.write(f"    lea str_{func}(%rip), %rdi\n")
            # Tail call to FatalMissingAPI
            fs.write(f"    jmp FatalMissingAPI\n\n")

        fs.write(".section .rodata\n")
        for func in func_list:
            fs.write(f"str_{func}: .asciz \"{func}\"\n")

    print("[+] Generated autogen_stubs.h and autogen_stubs.S successfully.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python UnityPlayerScan.py <path_to_UnityPlayer.dll>")
        sys.exit(1)
    generate_stubs(sys.argv[1])